version: '2'
catalog:
  name: Sistema Notificação
  version: 0.0.1
  description: Versão inicial
  questions:
    - variable: urlRegistry
      label: URL Registry
      description: URL da JHipster Registry para AutoDiscovery e Configuração centralizada
      default: registry.cnj-discovery
      required: true
      type: string
    - variable: registryPassword
      label: Senha admin da Registry
      description: Senha para acesso à interface e API da JHipster Registry
      default: admin
      required: true
      type: password
    - variable: registryAddress
      label: Endereço do Docker-Registry
      description: URL do Docker-Registry
      default: cnj-registry.basis.com.br
      required: true
      type: string
    - variable: tagRegistry
      label: Tag da Imagem
      description: Tag das imagens Docker na Docker-Registry
      default: latest
      required: true
      type: string
    - variable: createDatabase
      label: Criar os Bancos de Dados?
      description: Alguns ambientes não utilizarão banco de dados em container.
      default: true
      required: true
      type: boolean
    - variable: pwdPgsql
      label: Senha banco (usuário postgres)
      description: Senha do usuário postgres do banco de dados
      default: change_it
      required: true
      type: password
    - variable: pwdPgsqlNotificacao
      label: Senha banco notificacao
      description: Senha do usuário do banco de dados de notificacao
      default: notificacaoservice
      required: true
      type: password
    - variable: nfsCheck
      label: Usar NFS
      description: Se os volumes dos serviços utilizarem NFS, marcar esta caixa
      default: false
      required: true
      type: boolean
