version: '2'

{{- if eq .Values.nfsCheck "true" }}
volumes:
  sca-pgsql-servico:
    external: true
    driver: rancher-nfs
  sca-pgsql-gateway:
    external: true
    driver: rancher-nfs
  sca-elasticsearch-data:
    driver: rancher-nfs
    per_container: true
{{- end }}

services:
  {{- if eq .Values.createDatabase "true" }}
  pgsql-sca-servico-data:
    image: basis-registry.basis.com.br/postgres/pgsql-data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: "true"
    {{- if eq .Values.nfsCheck "true" }}
    volumes:
      - sca-pgsql-servico:/var/lib/postgresql/data
    {{- end }}

  pgsql-sca-servico:
    image: basis-registry.basis.com.br/comum/pgsql-br:9.5.5
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: pgsql-sca-servico-data
    volumes_from:
      - pgsql-sca-servico-data
    environment:
      - TZ=America/Sao_Paulo
      - DATABASE_NAME=scaservice
      - DATABASE_USER=scaservice
      - DATABASE_PASSWORD=${pwdPgsqlSca}
      - POSTGRES_PASSWORD=${pwdPgsql}

  pgsql-gateway-data:
    image: basis-registry.basis.com.br/postgres/pgsql-data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: "true"
    {{- if eq .Values.nfsCheck "true" }}
    volumes:
      - sca-pgsql-gateway:/var/lib/postgresql/data
    {{- end }}

  pgsql-gateway:
    image: basis-registry.basis.com.br/comum/pgsql-br:9.5.5
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: pgsql-gateway-data
    volumes_from:
      - pgsql-gateway-data
    environment:
      - TZ=America/Sao_Paulo
      - DATABASE_NAME=gateway
      - DATABASE_USER=gateway
      - DATABASE_PASSWORD=${pwdPgsqlGateway}
      - POSTGRES_PASSWORD=${pwdPgsql}
  {{- end }}

  sso:
    image: ${registryAddress}/sca/sso:${tagRegistry}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:${registryPassword}@${urlRegistry}:8761/eureka/
      - SSO_JDBC_URL=jdbc:postgresql://pgsql-sca-servico:5432/scaservice
      - SSO_JDBC_USERNAME=scaservice
      - SSO_JDBC_PASSWORD=${pwdPgsqlSca}
      - CAS_SERVER_NAME=${casServerName}
      - CAS_SERVER_PREFIX=${casServerPrefix}
      - SPRING_PROFILES_ACTIVE=prod,native
    {{- if eq .Values.createDatabase "true" }}
    depends_on: [pgsql-sca-servico]
    {{- end }}

  sca-servico:
    image: ${registryAddress}/sca/servico:${tagRegistry}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: glowroot-sidekick
      io.rancher.container.pull_image: always
    environment:
      - "JAVA_OPTS=-javaagent:/opt/glowroot/glowroot.jar -Dglowroot.agent.id=scaservico:: -Dglowroot.collector.address=http://central-collector.glowroot-central:8181 -server -Xmx2G -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
      - SPRING_CLOUD_CONFIG_URI=http://admin:${registryPassword}@${urlRegistry}:8761/config
      - TZ=America/Sao_Paulo
    depends_on:
      {{- if eq .Values.createDatabase "true" }}
      - pgsql-sca-servico
      {{- end }}
      - elasticsearch
      - glowroot-sidekick
    volumes_from:
      - glowroot-sidekick

  glowroot-sidekick:
    image: basis-registry.basis.com.br/basis/glowroot-sidekick:0.10.6
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: "true"

  gateway:
    image: ${registryAddress}/sca/gateway:${tagRegistry}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_CLOUD_CONFIG_URI=http://admin:${registryPassword}@${urlRegistry}:8761/config
    {{- if eq .Values.createDatabase "true" }}
    depends_on: [pgsql-gateway]
    {{- end }}

  cliente:
    image: ${registryAddress}/sca/cliente:${tagRegistry}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      - TZ=America/Sao_Paulo
      - ENDERECO_API=gateway:8080
    depends_on: [gateway]

  elasticsearch:
    image: elasticsearch:2.4.2
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      TZ: America/Sao_Paulo
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.path.conf=/usr/share/elasticsearch/config -Des.cluster.name=scacluster -Des.discovery.zen.minimum_master_nodes=1 -Des.discovery.zen.ping.unicast.hosts=elasticsearch"
    {{- if eq .Values.nfsCheck "true" }}
    volumes:
      - sca-elasticsearch-data:/usr/share/elasticsearch/data
    {{- end }}
