name: PJE-Status-Filiais
description: |
  Status de disponibilidade do Processo Judicial Eletronico - Tribunais
category: Application
maintainer: sergio.ramos@basis.com.br
license: proprietary
projectURL: http://www.cnj.jus.br

