version: '2'

catalog:
  name: BNMPv2 - Banco Nacional de Monitoramento de Prisão
  version: 0.1.1
  description: Stack para o Banco Nacional de Monitoramento de Prisão.
  questions:
    - variable: urlRegistry
      label: URL Registry
      description: URL da JHipster Registry para AutoDiscovery e Configuração centralizada
      default: registry.discovery
      required: true
      type: string

    - variable: registryPassword
      label: Senha admin da Registry
      description: Senha para acesso à interface e API da JHipster Registry
      default: admin
      required: true
      type: password

    - variable: registryAddress
      label: Endereço do Docker-Registry
      description: URL do Docker-Registry
      default: cnj-registry.basis.com.br
      required: true
      type: string

    - variable: tagRegistry
      label: Tag da Imagem
      description: Tag das imagens Docker na Docker-Registry
      default: latest
      required: true
      type: string

    - variable: nfsCheck
      label: Usar NFS
      description: Se os serviços não utilizarem volumes NFS, desmarcar esta caixa
      default: true
      required: true
      type: boolean

    - variable: createDatabase
      label: Criar os Bancos de Dados?
      description: Alguns ambientes não utilizarão banco de dados em container. Desmarcar se for o caso.
      default: true
      required: true
      type: boolean

    - variable: pwdPgsql
      label: Senha banco (usuário postgres)
      description: Senha do usuário postgres do banco de dados
      default: change_it
      required: true
      type: password

    - variable: pwdPgsqlGateway
      label: Senha banco gateway
      description: Senha do usuário do banco de dados do gateway
      default: gateway
      required: true
      type: password

    - variable: pwdPgsqlBnmp
      label: Senha banco bnmp
      description: Senha do usuário do banco de dados do bnmp
      default: bnmpv2
      required: true
      type: password
